#pragma once

#include "VulkanPlatform.h"
#include "VulkanCommon.h"

#ifndef AIR_VK_API_VERSION
#define AIR_VK_API_VERSION		VK_API_VERSION_1_0
#endif

#define VULKAN_HAS_DEBUGGING_ENABLED	(_DEBUG)

#ifndef VULKAN_USE_LLM
#define VULKAN_USE_LLM			((ENABLE_LOW_LEVEL_MEM_TRACHER) && VULKAN_SHOULD_USE_LLM)
#endif

#ifndef VULKAN_CUSTOM_MEMORY_MANAGER_ENABLED
#define VULKAN_CUSTOM_MEMORY_MANAGER_ENABLED VULKAN_USE_LLM
#endif

#if VULKAN_CUSTOM_MEMORY_MANAGER_ENABLED
#define VULKAN_CPU_ALLOCATOR			VulkanRHI::getMemoryAllocator(nullptr)
#else
#define VULKAN_CPU_ALLOCATOR			nullptr
#endif

#ifndef VULKAN_SUPPORTS_AMD_BUFFER_MARKER
#define VULKAN_SUPPORTS_AMD_BUFFER_MARKER	0
#endif

#ifndef VULKAN_SUPPORTS_NV_DIAGNOSTIC_CHECHPOINT
#define VULKAN_SUPPORTS_NV_DIAGNOSTIC_CHECHPOINT	0
#endif

#ifndef VULKAN_FREEPAGE_FOR_TYPE
#define VULKAN_FREEPAGE_FOR_TYPE		0
#endif

#define VULKAN_SUPPORTS_GPU_CRASH_DUMPS	(VULKAN_SUPPORTS_AMD_BUFFER_MARKER || VULKAN_SUPPORTS_NV_DIAGNOSTIC_CHECHPOINT)

