
SET_TARGET_PROPERTIES(${LIB_NAME} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY ${AIR_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${AIR_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${AIR_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO ${AIR_OUTPUT_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL ${AIR_OUTPUT_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${AIR_BIN_DIR}
	RUNTIME_OUTPUT_DIRECTORY_DEBUG ${AIR_BIN_DIR}
	RUNTIME_OUTPUT_DIRECTORY_RELEASE ${AIR_BIN_DIR}
	RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${AIR_BIN_DIR}
	RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${AIR_BIN_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${AIR_BIN_DIR}
	LIBRARY_OUTPUT_DIRECTORY_DEBUG ${AIR_BIN_DIR}
	LIBRARY_OUTPUT_DIRECTORY_RELEASE ${AIR_BIN_DIR}
	LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO ${AIR_BIN_DIR}
	LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL ${AIR_BIN_DIR}
    PROJECT_LABEL ${LIB_NAME}
    DEBUG_POSIFIX ${CMAKE_DEBUG_POSTFIX}
    OUTPUT_NAME ${LIB_NAME}-${AIR_PLATFORM_NAME}${DEBUG_POSIFIX}
)

